[workspace]
members = [ "crates/*" ]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
eyre = "0.6"
futures = "0.3"
paste = "1.0.15"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.47", features = ["full"] }
tracing = "0.1"
utoipa = "5.4"

[workspace.dependencies.alloy]
version = "1.0.23"
default-features = false
features = [
  "serde",
  "rlp",
  "contract",
  "signer-local",
  "providers",
  "rpc-types",
  "reqwest"
]
