[package]
name = "nomad"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
anyhow = "1.0.98"
toml = "0.8.22"
serde = { version = "1.0", features = ["derive"] }
libp2p = { version = "0.56", features = [
    "noise",
    "ping",
    "tcp",
    "tokio",
    "yamux",
] }
tokio = { version = "1.46.0", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3.30"
