[package]
name = "nomad-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "nomad"
path = "src/main.rs"

[dependencies]
nomad-types = { path = "../types" }
nomad-core = { path = "../core" }
nomad-rpc = { path = "../rpc" }
nomad-p2p = { path = "../p2p" }
nomad-ethereum = { path = "../ethereum" }

clap.workspace = true
anyhow.workspace = true
toml.workspace = true
serde.workspace = true
libp2p.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures.workspace = true
alloy.workspace = true
chrono.workspace = true
dotenvy.workspace = true
jsonrpsee.workspace = true
serde_json.workspace = true
reqwest.workspace = true
