[package]
name = "nomad-types"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives.workspace = true
eyre.workspace = true
paste.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
url.workspace = true
utoipa.workspace = true
