[package]
name = "nomad-vm"
version.workspace = true
edition.workspace = true

[dependencies]
opentelemetry.workspace = true
otel-instrument.workspace = true
tracing.workspace = true
thiserror.workspace = true
affair = "0.1.2"

