name: Rust Checks

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/rust.yml'
      - 'crates/**/*'
      - 'Cargo.*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v17
    - uses: nicknovitski/nix-develop@v1
    - run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v17
    - uses: nicknovitski/nix-develop@v1
    - uses: Swatinem/rust-cache@v2
    - name: Check node
      run: cargo clippy -- -Dwarnings
    - name: Check node built with nosgx
      run: cargo clippy --features nosgx -- -Dwarnings
    - name: Check enclave
      run: |
        cargo clippy --target x86_64-fortanix-unknown-sgx \
          -p nomad-enclave -- -Dwarnings

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v17
    - uses: nicknovitski/nix-develop@v1
    - uses: Swatinem/rust-cache@v2
    - run: cargo test --verbose

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v17
    - uses: nicknovitski/nix-develop@v1
    - uses: Swatinem/rust-cache@v2
    - name: Build Node
      run: cargo build --release
    - name: Build Enclave
      run: cargo build --target x86_64-fortanix-unknown-sgx -p nomad-enclave
